title: Datadog field mappings
order: 20
backends:
    - datadog
fieldmappings:
    ClientIP: '@network.client.ip'
    src_ip: '@network.client.ip'
    dst_ip: '@network.destination.ip'
    src_port: '@network.client.port'
    dst_port: '@network.destination.port'
    # '@network.bytes_read'
    # '@network.bytes_written'
    # '@network.client.geoip.country.name'
    # '@network.client.geoip.country.iso_code'
    # '@network.client.geoip.continent.code'
    # '@network.client.geoip.continent.name'
    # '@network.client.geoip.subdivision.name'
    # '@network.client.geoip.subdivision.iso_code'
    # '@network.client.geoip.city.name'
    c-uri: '@http.url'
    # '@http.status_code'
    # '@http.method'
    # '@http.referer'
    # '@http.request_id'
    c-useragent: '@http.useragent'
    # '@http.version'
    # '@http.url_details.host'
    # '@http.url_details.port'
    # '@http.url_details.path'
    # '@http.url_details.queryString'
    # '@http.url_details.scheme'
    # '@http.useragent_details.os.family'
    # '@http.useragent_details.browser.family'
    # '@http.useragent_details.device.family'
    # '@error.kind'
    # '@error.message'
    # '@error.stack'
    # '@db.instance'
    # '@db.statement'
    # '@db.operation'
    # '@db.user'
    # '@duration'
    # '@usr.id'
    # '@usr.name'
    # '@usr.email'
    # '@dns.id'
    query: '@dns.question.name'
    parent_domain: '@dns.question.name'
    dns_query: '@dns.question.type'
    record_type: '@dns.question.type'
    # '@dns.question.class'
    question_length: '@dns.question.size'
    # '@dns.answer.name'
    # '@dns.answer.type'
    # '@dns.answer.class'
    # '@dns.answer.size'
    # '@dns.flags.rcode'
    category: '@evt.name'
    eventSource: '@eventSource'
    eventName: '@eventName'
    action: '@evt.outcome'
    Command: '@system.cmd'
